# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-clinvap-1.0dev
channels:
  - bioconda
  - anaconda
  - https://conda.anaconda.org/openeye
  - anaconda-fusion
  - conda-forge
  - defaults
dependencies:
  - r-markdown=1.1
  - ensembl-vep=95.3
  - bcftools=1.9
  - astroid=2.4.1
  - autopep8=1.4.4
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - coloredlogs=10.0
  - cryptography=2.9.2
  - curl=7.69.1
  - cyvcf2=0.11.6
  - htslib=1.9
  - humanfriendly=6.1
  - idna=2.9
  - intel-openmp=2019.4
  - isort=4.3.21
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - libcurl=7.69.1
  - libdeflate=1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libssh2=1.9.0
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - pip=20.0.2
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pylint=2.5.2
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=8.0
  - requests=2.23.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - toml=0.10.0
  - typed-ast=1.4.1
  - urllib3=1.25.8
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.5
  - zlib=1.2.11
  - docxtpl=0.10.0
